services:
  db_postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: master
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: ticketing
  keycloack:
    image: quay.io/keycloak/keycloak:21.1.1
    ports:
      - 8080:8080
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: ticketing
      DB_USER: master
      DB_SCHEMA: public
      DB_PASSWORD: pass
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    volumes:
      - ./realm-export.json:/tmp/realm-export.json