#KEYCLOACK CONFIGURATIONS
keycloak:
  server: http://localhost:8080
  realm:
    name: anmil-realm


logging:
  level:
    org:
      springframework:
        security: DEBUG

#POSTGRESQL CONFIGURATIONS
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ticketing
    username: master
    password: pass
  security:
    oauth2:
      client:
        registration:
          keycloak:
            authorization-grant-type: authorization_code
            client-id: anmil-grant-access
            client-secret: prova-secret
            provider: keycloak
            scope: openid,profile,email,offline_access
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/${keycloak.realm.name}
            token-uri: http://localhost:8080/realms/${keycloak.realm.name}/protocol/openid-connect/token
            user-info-uri: http://localhost:8080/realms/${keycloak.realm.name}/protocol/openid-connect/userinfo
            jwk-set-uri: http://localhost:8080/realms/${keycloak.realm.name}/protocol/openid-connect/certs
            user-name-attribute: preferred_username

#SERVER CONFIGURATION
server:
  port: 8081